name: 'Recce Cloud CI/CD Action'

description: 'A GitHub Action to integrate Recce Cloud CI/CD from your GitHub repository.'

author: 'Recce Team'

branding:
  icon: 'upload-cloud'
  color: 'orange'

inputs:
  dbt_target_path:
    description: 'The path to the DBT target directory containing manifest.json and catalog.json (default: target).'
    required: true
    default: 'target'

  base_branch:
    description: 'The base branch for the deployment (default: main).'
    required: false
    default: 'main'

  api_host:
    description: 'The Recce Cloud API host URL.'
    required: false
    default: 'https://cloud.datarecce.io' 

runs:
  using: "composite"
  steps:
    - name: 'Verify DBT manifest files'
      shell: bash
      run: |
        if [[ ! -f "${{ inputs.dbt_target_path }}/manifest.json" ]]; then
          echo "Error: DBT manifest.json file not found in ${{ inputs.dbt_target_path }} directory."
          echo "### Recce Cloud CI/CD Action Error ###\nThe DBT `manifest.json` file is missing. Please ensure that your DBT project has been built and the manifest.json file is present in the specified target directory.\n### End of Error ###" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        if [[ ! -f "${{ inputs.dbt_target_path }}/catalog.json" ]]; then
          echo "Error: DBT catalog.json file not found in ${{ inputs.dbt_target_path }} directory."
          echo "### Recce Cloud CI/CD Action Error ###\nThe DBT `catalog.json` file is missing. Please ensure that your DBT project has been built and the catalog.json file is present in the specified target directory.\n### End of Error ###" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        echo "DBT manifest files verified."
        

    - name: 'Upload Manifest to Recce Cloud Session'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}  # Must explicitly set this
      run: |
        adapter_type=$(cat ${{ inputs.dbt_target_path }}/manifest.json | jq -r '.metadata.adapter_type')

        # Verify Recce Cloud Integration Settings
        response=$(curl -s -X GET -H "Authorization: Bearer $GITHUB_TOKEN" "${{ inputs.api_host }}/api/v2/github/${{ github.repository }}/verify-token")
        project_id=$(echo "$response" | jq -r '.project_id')
        organization_id=$(echo "$response" | jq -r '.organization_id')

        # Get the presigned URLs for uploading the manifest files
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "Uploading manifest for Pull Request session..."
          branch_name="${{ github.head_ref }}"
          pr_number="${{ github.event.number }}"
          response=$(curl -s -X POST -H "Authorization: Bearer ${{ inputs.recce_token }}" -H "Content-Type: application/json" -d '{
            "branch": "'"$branch_name"'",
            "pr_number": "'"$pr_number"'",
            "adapter_type": "'"$adapter_type"'",
          }' "${{ inputs.api_host }}/api/v2/organizations/$organization_id/projects/$project_id/pr-branch-session" )
        else
          echo "Uploading manifest for base session..."
          branch_name="${{ github.ref_name }}"
          response=$(curl -s -X POST -H "Authorization: Bearer ${{ inputs.recce_token }}" -H "Content-Type: application/json" -d '{
            "branch": "'"$branch_name"'",
            "adapter_type": "'"$adapter_type"'",
          }' "${{ inputs.api_host }}/api/v2/organizations/$organization_id/projects/$project_id/pr-branch-session" )
        fi

        # Upload the manifest.json file
        manifest_upload_url=$(echo "$response" | jq -r '.manifest_upload_url')
        catalog_upload_url=$(echo "$response" | jq -r '.catalog_upload_url')
        session_id=$(echo "$response" | jq -r '.session_id')
        if [[ "$manifest_upload_url" == "null" || "$catalog_upload_url" == "null" || "$session_id" == "null" ]]; then
          echo "Error: Failed to get upload URLs or session ID from Recce Cloud."
          echo "### Recce Cloud CI/CD Action Error ###\nFailed to get upload URLs or session ID from Recce Cloud. Please check your Recce token and repository integration settings.\n### End of Error ###" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
        curl -s -X PUT -H "Content-Type: application/json" --upload-file "${{ inputs.dbt_target_path }}/manifest.json" "$manifest_upload_url"
        curl -s -X PUT -H "Content-Type: application/json" --upload-file "${{ inputs.dbt_target_path }}/catalog.json" "$catalog_upload_url"
        echo "Manifest files uploaded to Recce Cloud."
